# Generated by Django 3.2.7 on 2021-10-03 23:46

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employeetree'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AlterField(
            model_name='employeetree',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='employee.employeetree'),
        ),
    ]
