# Generated by Django 3.2.7 on 2021-10-13 12:24

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_employeetree_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetree',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='employee.employeetree'),
        ),
    ]
